version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/setup.sql:/docker-entrypoint-initdb.d/a.sql
      - ./db/sql/ddl_create_tables.sql:/docker-entrypoint-initdb.d/b.sql